//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H5pPlayer.Resources.View.ValidateH5p {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidateH5pView_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidateH5pView_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H5pPlayer.Resources.View.ValidateH5p.ValidateH5pView.en", typeof(ValidateH5pView_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H5P is primitive.
        /// </summary>
        internal static string Validation_Button_Primitive {
            get {
                return ResourceManager.GetString("Validation.Button.Primitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark H5P as “primitive”.
        /// </summary>
        internal static string Validation_Button_PrimitiveAria {
            get {
                return ResourceManager.GetString("Validation.Button.PrimitiveAria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H5P is not usable.
        /// </summary>
        internal static string Validation_Button_Unusable {
            get {
                return ResourceManager.GetString("Validation.Button.Unusable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H5P is completable.
        /// </summary>
        internal static string Validation_CompletableLabel {
            get {
                return ResourceManager.GetString("Validation.CompletableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H5P Validation.
        /// </summary>
        internal static string Validation_HeaderTitle {
            get {
                return ResourceManager.GetString("Validation.HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep this window open until validation is complete!.
        /// </summary>
        internal static string Validation_WarningKeepOpen {
            get {
                return ResourceManager.GetString("Validation.WarningKeepOpen", resourceCulture);
            }
        }
    }
}
