namespace PersistEntities.LearningContent.Question;

/// <summary>
/// Represents a multiple choice question with either single or multiple responses.
/// </summary>
public interface IMultipleChoiceQuestionPe : IAdaptivityQuestionPe
{
    /// <summary>
    /// Choices for the question to pick response from.
    /// </summary>
    public ICollection<Choice> Choices { get; set; }

    /// <summary>
    /// Correct choices from <see cref="Choices"/>.
    /// May be single item for <see cref="MultipleChoiceSingleResponseQuestionPe"/>
    /// or multiple items for <see cref="MultipleChoiceMultipleResponseQuestionPe"/>.
    /// </summary>
    /// <remarks>When implementing class is <see cref="MultipleChoiceSingleResponseQuestionPe"/>, this is an autogenerated
    /// property and changes to the collection will be overridden.</remarks>
    public ICollection<Choice> CorrectChoices { get; }

    /// <summary>
    /// The main question text of the question.
    /// </summary>
    public string Text { get; set; }
}