##this is the first Test Database

[FirstTable]
FirstKey = "First Database, First Table, First Key"
SecondKey = "First Database, First Table, Second Key"
table_empty = false

[SecondTable]
FirstKey = "First Database, Second Table, First Key"
SecondKey = "First Database, Second Table, Second Key"
table_empty = false
