name: Coveralls Code Coverage
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: windows-latest
    env:
      dotNetVersion: net6.0
      dotNetConfiguration: Release
      runtimeTarget: win-x86
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      # install dependencies, build, and test
      - name: Setup Dotnet for use with actions
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          
      - name: Cache Nuget Packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
          
      #- name: Run automated unit and integration test
      #  run: dotnet test AuthoringToolTest\AuthoringToolTest.csproj --configuration Release --results-directory ${{ github.workspace }}/TestResults /p:CollectCoverage=true CoverletOutput=${{ github.workspace }}/TestResults/ /p:MergeWith=${{ github.workspace }}/TestResults/coverlet.info /p:CoverletOutputFormat=lcov --% /p:Include=\"[AuthoringTool]*,[AuthoringToolLib]*,[Generator]*\" /p:Exclude=\"[ElectronWrapper]*,[ElectronWrapper.*]*,[AuthoringToolTest.*]*,[AuthoringToolTest]*,[GeneratorTest]*,[AuthoringToolLibTest]\"
      - name: Run automated unit and integration test AuthoringTool
        run: dotnet test AuthoringToolTest\AuthoringToolTest.csproj --configuration Release --results-directory D:/a/Autorentool/TestResults/ /p:CollectCoverage=true /p:CoverletOutput=D:\a\Autorentool\Autorentool/TestResults/coverlet.info /p:CoverletOutputFormat=lcov --% /p:Include=\"[AuthoringTool]*\" /p:Exclude=\"[ElectronWrapper]*,[ElectronWrapper.*]*,[AuthoringToolTest.*]*,[AuthoringToolTest]*,[GeneratorTest]*,[AuthoringToolLibTest]\"
      
      - name: Run automated unit and integration test AuthoringToolLib
        run: dotnet test AuthoringToolLibTest\AuthoringToolLibTest.csproj --configuration Release --results-directory D:/a/Autorentool/TestResults/ /p:CollectCoverage=true /p:MergeWith=D:/a/Autorentool/TestResults/coverlet.info /p:CoverletOutputFormat=lcov --% /p:Include=\"[AuthoringToolLib]*\" /p:Exclude=\"[ElectronWrapper]*,[ElectronWrapper.*]*,[AuthoringToolTest.*]*,[AuthoringToolTest]*,[GeneratorTest]*,[AuthoringToolLibTest]\"
        
      - name: Run automated unit and integration test Generator
        run: dotnet test GeneratorTest\GeneratorTest.csproj --configuration Release --results-directory D:/a/Autorentool/TestResults/ /p:CollectCoverage=true /p:MergeWith=D:/a/Autorentool/TestResults/coverlet.info /p:CoverletOutputFormat=lcov --% /p:Include=\"[Generator]*\" /p:Exclude=\"[ElectronWrapper]*,[ElectronWrapper.*]*,[AuthoringToolTest.*]*,[AuthoringToolTest]*,[GeneratorTest]*,[AuthoringToolLibTest]\"
        
      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #path-to-lcov: .\AuthoringToolTest\TestResults\coverlet.info 
          path-to-lcov: D:/a/Autorentool/TestResults/coverlet.info 
