name: Coveralls Code Coverage
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: windows-latest
    env:
      dotNetVersion: net6.0
      dotNetConfiguration: Release
      runtimeTarget: win-x86
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      # install dependencies, build, and test
      - name: Setup Dotnet for use with actions
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          
      - name: Cache Nuget Packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
          
      - name: Run automated unit and integration test AuthoringTool
        run: dotnet test AuthoringToolTest\AuthoringToolTest.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=${{ github.workspace }}\TestResults\AuthoringToolTest_coverlet.info /p:CoverletOutputFormat=lcov --% /p:Include=\"[AuthoringTool]*\" /p:Exclude=\"[ElectronWrapper]*,[ElectronWrapper.*]*,[AuthoringToolTest.*]*,[AuthoringToolTest]*,[GeneratorTest]*,[AuthoringToolLibTest]\"
      
      #- name: Run automated unit and integration test AuthoringToolLib
      #  run: dotnet test AuthoringToolLibTest\AuthoringToolLibTest.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=${{ github.workspace }}\TestResults\AuthoringToolLibTest_coverlet.info /p:CoverletOutputFormat=lcov --% /p:Include=\"[AuthoringToolLib]*\" /p:Exclude=\"[ElectronWrapper]*,[ElectronWrapper.*]*,[AuthoringToolTest.*]*,[AuthoringToolTest]*,[GeneratorTest]*,[AuthoringToolLibTest]\"
        
      #- name: Run automated unit and integration test Generator
      #  run: dotnet test GeneratorTest\GeneratorTest.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=${{ github.workspace }}\TestResults\Generator_coverlet.info /p:CoverletOutputFormat=lcov --% /p:Include=\"[Generator]*\" /p:Exclude=\"[ElectronWrapper]*,[ElectronWrapper.*]*,[AuthoringToolTest.*]*,[AuthoringToolTest]*,[GeneratorTest]*,[AuthoringToolLibTest]\"
        
      #- name: Merge Coverage Reports
      #  run: dotnet tool install --global dotnet-reportgenerator-globaltool --version <version-number>; reportgenerator -reports:${{ github.workspace }}\TestResults   -targetdir:<output-directory>/CoverageReport -reporttypes:Cobertura
        
        
      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}\TestResults\coverlet.info 
