name: OSX Application Build
on: 
  workflow_dispatch: 
  label:
    types:
      - created

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      # install dependencies, build, and test
      - name: Setup Dotnet for use with actions
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            5.x
            6.x
        
      - name: Cache Nuget Packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
            
      - name: Set up npm
        uses: actions/setup-node
        with: 
          node-version: '16'
      
      - name: Install electronize
        run: dotnet tool restore
        
      - name: Build AuthoringTool binary
        working-directory: ./AuthoringTool
        run: dotnet electronize build /target osx
        
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: authoringtool-osx
          path: ./AuthoringTool/bin/Desktop_Publish/