name: Run tests
on: 
  push:
    branches:
      - main
  pull_request:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-18.04, ubuntu-20.04, windows-latest, macos-latest]
    env:
      dotNetVersion: net6.0
      dotNetConfiguration: Release
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      # install dependencies, build, and test
      - name: Setup Dotnet for use with actions
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      - name: Cache Nuget Packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Run automated unit and integration tests
        run: dotnet test 

  publish-osx:
    needs: test
    name: Publish for MacOS
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup Dotnet for use with actions
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            5.x
            6.x

      - name: Cache Nuget Packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: macOS-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            macOS-nuget

      - name: Set up npm
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install electronize
        run: dotnet tool restore

      - name: Build AuthoringTool binary
        working-directory: ./AuthoringTool
        run: dotnet electronize build /target osx

      - name: Save Build folder
        uses: actions/upload-artifact@v3
        with:
          name: authoringtool-osx
          path: ./AuthoringTool/bin/Desktop_Publish/AuthoringTool-*.dmg
          if-no-files-found: error
  
  publish-windows:
    needs: test
    name: Publish for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup Dotnet for use with actions
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            5.x
            6.x

      - name: Cache Nuget Packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: Windows-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            Windows-nuget

      - name: Set up npm
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install electronize
        run: dotnet tool restore

      - name: Build AuthoringTool binary
        working-directory: ./AuthoringTool
        run: dotnet electronize build /target win

      - name: Save Build folder
        uses: actions/upload-artifact@v3
        with:
          name: authoringtool-win
          path: ./AuthoringTool/bin/Desktop_Publish/AuthoringTool*.exe
          if-no-files-found: error
  
  publish-linux:
    needs: test
    name: Publish for Linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup Dotnet for use with actions
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            5.x
            6.x

      - name: Cache Nuget Packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: Linux-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            Linux-nuget

      - name: Set up npm
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install electronize
        run: dotnet tool restore
        
      - name: Build AuthoringTool binary
        working-directory: ./AuthoringTool
        run: dotnet electronize build /target linux
        
      - name: Save Build folder
        uses: actions/upload-artifact@v3
        with:
          name: authoringtool-linux
          path: ./AuthoringTool/bin/Desktop_Publish/
          if-no-files-found: error
