#ProjektAdler AuthoringTool Language Database -- Language: English

Database_Name = "AuthoringTool String Database: English"
Database_Language = "en"

[AuthoringTool]
Index_GetStarted = 'Please click on the "Workspace" button to the left to get started.'
table_empty = false

[BusinessLogic]
table_empty = true

[DataAccess]
table_empty = true

[ElectronWrapper]
table_empty = true

[Generator]
table_empty = true

[PersistEntities]
table_empty = true

[Presentation]
table_empty = true

[Shared]
table_empty = true

[BlazorMainLayout]
LanguageSwitchLanguage = "Language"
table_empty = false



